# Generated by Django 4.2 on 2023-10-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lung', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='LungCancer',
        ),
    ]
